sudo: required
services:
    - docker
before_install:
    - docker build -t jagwinderkaurd/docker-react-new -f Dockerfile.dev .
   
script:
    - docker run jagwinderkaurd/docker-react-new npm run test -- --coverage